apiVersion: apps/v1
kind: Deployment
metadata:
  name: sbapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sbapp
  template:
    metadata:
      labels:
        app: sbapp
    spec:
      containers:
        - name: sbapp
          image: fra.ocir.io/frol67eoawud/spring-projects/spring-boot-hello-app:latest
          imagePullPolicy: Always
          ports:
            - name: sbapp
              containerPort: 8080
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: sbapp-lb
  labels:
    app: sbapp
  annotations:
    service.beta.kubernetes.io/oci-load-balancer-shape: "flexible"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: "10"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: "10"
spec:
  type: LoadBalancer
  selector:
    app: sbapp
  ports:
    - port: 8080

